# Download Historic Realtime Wind Data from NOAA

Description: https://www.ndbc.noaa.gov/station_realtime.php?station=burl1

In [1]:
import requests
import pandas as pd
from datetime import datetime
import re
from pathlib import Path
from zoneinfo import ZoneInfo

In [2]:
station = "nwcl1"
api = f"https://www.ndbc.noaa.gov/data/realtime2/{station.upper()}.txt"
path = "./windData"
api

'https://www.ndbc.noaa.gov/data/realtime2/NWCL1.txt'

In [3]:
def lp(v):
    print(f"[{datetime.now()}] {v}")

lp("Starting...")

[2026-07-09 09:11:09.281302] Starting...

In [4]:
lp(api)

[2026-07-09 09:11:09.286685] https://www.ndbc.noaa.gov/data/realtime2/NWCL1.txt

In [5]:
resp = requests.get(api)

In [6]:
resp.raise_for_status()

In [7]:
data = resp.text.splitlines()
data[:5]

['#YY  MM DD hh mm WDIR WSPD GST  WVHT   DPD   APD MWD   PRES  ATMP  WTMP  DEWP  VIS PTDY  TIDE',
 '#yr  mo dy hr mn degT m/s  m/s     m   sec   sec degT   hPa  degC  degC  degC  nmi  hPa    ft',
 '2026 07 09 13 30  MM  0.0  1.0    MM    MM    MM  MM 1018.7  30.1  30.9    MM   MM   MM    MM',
 '2026 07 09 13 24  10  0.5  1.5    MM    MM    MM  MM 1018.7  29.8  30.9    MM   MM   MM    MM',
 '2026 07 09 13 18 260  1.0  1.5    MM    MM    MM  MM 1018.6    MM  30.9    MM   MM   MM    MM']

In [8]:
reg = re.compile(r"\s+")
dataSplit = list(map(reg.split, data))
dataSplit[:5]

[['#YY',
  'MM',
  'DD',
  'hh',
  'mm',
  'WDIR',
  'WSPD',
  'GST',
  'WVHT',
  'DPD',
  'APD',
  'MWD',
  'PRES',
  'ATMP',
  'WTMP',
  'DEWP',
  'VIS',
  'PTDY',
  'TIDE'],
 ['#yr',
  'mo',
  'dy',
  'hr',
  'mn',
  'degT',
  'm/s',
  'm/s',
  'm',
  'sec',
  'sec',
  'degT',
  'hPa',
  'degC',
  'degC',
  'degC',
  'nmi',
  'hPa',
  'ft'],
 ['2026',
  '07',
  '09',
  '13',
  '30',
  'MM',
  '0.0',
  '1.0',
  'MM',
  'MM',
  'MM',
  'MM',
  '1018.7',
  '30.1',
  '30.9',
  'MM',
  'MM',
  'MM',
  'MM'],
 ['2026',
  '07',
  '09',
  '13',
  '24',
  '10',
  '0.5',
  '1.5',
  'MM',
  'MM',
  'MM',
  'MM',
  '1018.7',
  '29.8',
  '30.9',
  'MM',
  'MM',
  'MM',
  'MM'],
 ['2026',
  '07',
  '09',
  '13',
  '18',
  '260',
  '1.0',
  '1.5',
  'MM',
  'MM',
  'MM',
  'MM',
  '1018.6',
  'MM',
  '30.9',
  'MM',
  'MM',
  'MM',
  'MM']]

In [9]:
dataDf = pd.DataFrame(dataSplit[2:], columns=dataSplit[0])

for col in dataDf.columns:
    dataDf.loc[dataDf[col] == 'MM',col] = None

dataDf = dataDf.astype({col:float for col in dataSplit[0]})

In [10]:
dataDf.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,PTDY,TIDE
0,2026.0,7.0,9.0,13.0,30.0,NaN,0.0,1.0,NaN,NaN,NaN,NaN,1018.7,30.1,30.9,NaN,NaN,NaN,NaN
1,2026.0,7.0,9.0,13.0,24.0,10.0,0.5,1.5,NaN,NaN,NaN,NaN,1018.7,29.8,30.9,NaN,NaN,NaN,NaN
2,2026.0,7.0,9.0,13.0,18.0,260.0,1.0,1.5,NaN,NaN,NaN,NaN,1018.6,NaN,30.9,NaN,NaN,NaN,NaN
3,2026.0,7.0,9.0,13.0,12.0,230.0,1.5,2.1,NaN,NaN,NaN,NaN,1018.6,NaN,30.9,NaN,NaN,NaN,NaN
4,2026.0,7.0,9.0,13.0,6.0,230.0,1.0,1.5,NaN,NaN,NaN,NaN,1018.5,NaN,30.9,NaN,NaN,NaN,NaN

In [11]:
dataDf = dataDf.astype({col:pd.Int64Dtype() for col in dataDf.columns[ dataDf.mod(1).max() == 0 ].to_list()})
dataDf.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,PTDY,TIDE
0,2026,7,9,13,30,<NA>,0.0,1.0,NaN,NaN,NaN,NaN,1018.7,30.1,30.9,NaN,NaN,NaN,NaN
1,2026,7,9,13,24,10,0.5,1.5,NaN,NaN,NaN,NaN,1018.7,29.8,30.9,NaN,NaN,NaN,NaN
2,2026,7,9,13,18,260,1.0,1.5,NaN,NaN,NaN,NaN,1018.6,NaN,30.9,NaN,NaN,NaN,NaN
3,2026,7,9,13,12,230,1.5,2.1,NaN,NaN,NaN,NaN,1018.6,NaN,30.9,NaN,NaN,NaN,NaN
4,2026,7,9,13,6,230,1.0,1.5,NaN,NaN,NaN,NaN,1018.5,NaN,30.9,NaN,NaN,NaN,NaN

In [12]:
dataDf.dtypes

#YY       Int64
MM        Int64
DD        Int64
hh        Int64
mm        Int64
WDIR      Int64
WSPD    float64
GST     float64
WVHT    float64
DPD     float64
APD     float64
MWD     float64
PRES    float64
ATMP    float64
WTMP    float64
DEWP    float64
VIS     float64
PTDY    float64
TIDE    float64
dtype: object

In [13]:
tz = ZoneInfo("America/Chicago")
utcTz = ZoneInfo("UTC")
def makeDate(row):
    
    dateOut = datetime(int(row['#YY']),\
                       int(row['MM']),\
                       int(row['DD']),\
                       int(row['hh']),\
                       int(row['mm']),\
                       tzinfo=utcTz).astimezone(tz)
    
    
    return dateOut
    
dataDf.index = dataDf.apply(makeDate, axis=1)

In [14]:
dataDf.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,PTDY,TIDE
2026-07-09 08:30:00-05:00,2026,7,9,13,30,<NA>,0.0,1.0,NaN,NaN,NaN,NaN,1018.7,30.1,30.9,NaN,NaN,NaN,NaN
2026-07-09 08:24:00-05:00,2026,7,9,13,24,10,0.5,1.5,NaN,NaN,NaN,NaN,1018.7,29.8,30.9,NaN,NaN,NaN,NaN
2026-07-09 08:18:00-05:00,2026,7,9,13,18,260,1.0,1.5,NaN,NaN,NaN,NaN,1018.6,NaN,30.9,NaN,NaN,NaN,NaN
2026-07-09 08:12:00-05:00,2026,7,9,13,12,230,1.5,2.1,NaN,NaN,NaN,NaN,1018.6,NaN,30.9,NaN,NaN,NaN,NaN
2026-07-09 08:06:00-05:00,2026,7,9,13,6,230,1.0,1.5,NaN,NaN,NaN,NaN,1018.5,NaN,30.9,NaN,NaN,NaN,NaN

In [15]:
lp(f"Start: {dataDf.index.min()}\t\tStop: {dataDf.index.max()}")

[2026-07-09 09:11:11.159265] Start: 2026-05-24 19:00:00-05:00		Stop: 2026-07-09 08:30:00-05:00

In [16]:
Path(path).mkdir(exist_ok=True)

In [17]:
saveNameBase = f"{station}_{dataDf.index.max().strftime("%Y-%m-%d")}"
saveNamePickle = saveNameBase + ".pickle"
saveNameCSV = saveNameBase + ".csv"

lp(f"Saving to {saveNamePickle}")
dataDf.to_pickle(f"{path}/{saveNamePickle}")

lp(f"Saving to {saveNameCSV}")
dataDf.to_csv(f"{path}/{saveNameCSV}")

[2026-07-09 09:11:11.168373] Saving to nwcl1_2026-07-09.pickle
[2026-07-09 09:11:11.170073] Saving to nwcl1_2026-07-09.csv

In [18]:
lp("Finished")

[2026-07-09 09:11:11.319739] Finished